// GENERATED by scripts/load — do not edit. Proves scripts/parity/scheduled.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/parity/scheduled.ts", async () => {
  const mod = await import("../../scripts/parity/scheduled.js");
  expect(mod).toBeDefined();
});
